name: phpunit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4']

    steps:

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: touch package-lock.json
      run: |
        touch package-lock.json
        touch package.json

    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: npm

    - name: install htmlhint
      run: |
        npm install htmlhint

    - name: Checkout
      uses: actions/checkout@v2

    - name: copy environment for workflow
      run: |
        cp -p .env.workflow .env

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test-workflow
      id: run-test
      continue-on-error: true

    - name: Upload Unit Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: results/*.xml

    - name: Download Artifacts
      if: success() || failure()
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: artifacts/**/*.xml

    - name: Failed workflow if test was failed
      if: ${{ steps.run-test.outcome == 'failure' }}
      run: |
        echo "Error: test was failed"
        exit 1


